import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "styles/globals.css";

export const metadata: Metadata = {
  title: "HiWEB Task",
  description: "Generated by create next app",
  icons: {
    icon: "/hiweb-logo.png",
  },
};

const vazirFont = Vazirmatn({ subsets: ["latin"] });

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html dir="rtl" lang="fa">
      <body className={vazirFont.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
